/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'disable',
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./node_modules/flowbite/**/*.js",
  ],
  theme: {
    extend: {
      screens: {
        '2k': '2560px',
        'fhd': '1920px',
        'laptop': '1366px',
        'hd': '1280px',
        'tab': '800px',
        'phone': '375px',
      },
      colors: {
        'dark-blue' : '#000F8A',
        'darker-blue' : '#000864',
        'light-brown' : '#DEAA51',
        'dark-brown' : '#B57E1D',
        'grey' : '#838383',
        'light-blue' : '#A4AADC',
        'light-black' : '#2C2C2C',
        'lighter-blue' : '#C8CEFC',
        'lightest-blue' : '#E4E7FF',
        'blue-light' : '#98A1FF',
        'light-grey' : '#D9D9D9',
        'lightest-grey': '#B9C0F4',
        'profile-grey': '#F8F8F8',
        'red-alert': '#F4D2D5',
        'ligt-black' : '#1E1E1E',
        'light-green': '#1CD22E',
        'lighter-green': '#D4F9CB',
        'dark-yellow': '#CB9713',
        'dark-red': '#B52809'
      },
      fontSize: {
        sm: '0.938rem',
        base: '1rem',
        xl: '1.25rem',
        '2xl': '1.563rem',
        '3xl': '2.25rem',
        '4xl': '2.875rem',
        '5xl': '3.052rem',
      },
      lineHeight: {
        'extra-loose': '2.5',
        '11': '2.875rem',
      },
      backgroundPosition: {
        'top-min-1': 'center top -0.25rem',
        'top-min-2': 'center top -0.5rem',
        'top-min-3': 'center top -0.75rem',
        'top-min-4': 'center top -1rem',
        'top-min-5': 'center top -1.25rem',
        'top-min-6': 'center top -1.5rem',
        'top-min-7': 'center top -1.75rem',
        'top-min-8': 'center top -2rem',
        'top-min-9': 'center top -2.25rem',
        'top-min-10': 'center top -2.5rem',
        'top-min-11': 'center top -2.75rem',
        'top-min-12': 'center top -3rem',
        'top-min-14': 'center top -3.25rem',
        'top-min-16': 'center top -4rem',
        'top-min-20': 'center top -5rem',
        'top-min-24': 'center top -6rem',
        'top-min-28': 'center top -7rem',
        'top-min-32': 'center top -8rem',
        'top-min-36': 'center top -9rem',
        'top-min-40': 'center top -10rem',
        'top-min-44': 'center top -11rem',
        'top-min-48': 'center top -12rem',
        'top-min-52': 'center top -13rem',
        'top-min-56': 'center top -14rem',
        'top-min-60': 'center top -15rem',
        'top-min-64': 'center top -16rem',
        'top-min-68': 'center top -17rem',
        'top-min-72': 'center top -18rem',
        'top-min-76': 'center top -19rem',
        'top-min-80': 'center top -20rem',
        'top-min-84': 'center top -21rem',
        'top-min-88': 'center top -22rem',
        'top-min-92': 'center top -23rem',
        'top-min-96': 'center top -24rem',
        'right-min-1': 'right -0.25rem center',
        'right-min-2': 'right -0.5rem center',
        'right-min-3': 'right -0.75rem center',
        'right-min-4': 'right -1rem center',
        'right-min-5': 'right -1.25rem center',
        'right-min-6': 'right -1.5rem center',
        'right-min-7': 'right -1.75rem center',
        'right-min-8': 'right -2rem center',
        'right-min-9': 'right -2.25rem center',
        'right-min-10': 'right -2.5rem center',
        'right-min-11': 'right -2.75rem center',
        'right-min-12': 'right -3rem center',
        'right-min-14': 'right -3.25rem center',
        'right-min-16': 'right -4rem center',
        'right-min-20': 'right -5rem center',
        'right-min-24': 'right -6rem center',
        'right-min-28': 'right -7rem center',
        'right-min-32': 'right -8rem center',
        'right-min-36': 'right -9rem center',
        'right-min-40': 'right -10rem center',
        'right-min-44': 'right -11rem center',
        'right-min-48': 'right -12rem center',
        'right-min-52': 'right -13rem center',
        'right-min-56': 'right -14rem center',
        'right-min-60': 'right -15rem center',
        'right-min-64': 'right -16rem center',
        'right-min-68': 'right -17rem center',
        'right-min-72': 'right -18rem center',
        'right-min-76': 'right -19rem center',
        'right-min-80': 'right -20rem center',
        'right-min-84': 'right -21rem center',
        'right-min-88': 'right -22rem center',
        'right-min-92': 'right -23rem center',
        'right-min-96': 'right -24rem center',
      },
      fontFamily: {
        'intelOne': ['IntelOne', 'sans'], // 'sans' is a fallback font
      },
      fontWeight: {
        '300': '300',
        '500': '500',
        'bold': '700',
      },
    },
  },
  variants: {
    extend: {
      display: ['responsive']
    }
  },
  plugins: [
    require('flowbite/plugin'),
  ],
}
